# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-25 20:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.fields.TextField(),
        ),
    ]
