# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-04 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20160725_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(default=b'comment', max_length=25000),
        ),
    ]
