# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-18 14:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0003_auto_20160809_1407'),
        ('comment', '0003_auto_20160804_1131'),
    ]

    operations = [
    ]
