# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-30 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TempComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=255)),
                ('google_id', models.CharField(max_length=512)),
                ('parent_google_id', models.CharField(max_length=512)),
                ('creation_date', models.DateTimeField()),
                ('text', models.TextField()),
            ],
        ),
    ]
