# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-14 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('temp_comment', '0002_tempcomment_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tempcomment',
            name='article',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='old_comments', to='article.Article'),
        ),
    ]
