version: '2'
services:
  thumbor:
    image: apsl/thumbor
    domainname: redegsti.dev
    hostname: thumbor
    environment:
      AUTO_WEBP: "False"
      USE_GIFSICLE_ENGINE: "True"
      MAX_AGE: 5000
      MAX_AGE_TEMP_IMAGE: 240
      MAX_SOURCE_SIZE: 500
      QUALITY: 100
      DETECTORS: "['thumbor.detectors.face_detector','thumbor.detectors.feature_detector']"
      LOADER: 'thumbor.loaders.http_loader'
      FACE_DETECTOR_CASCADE_FILE: 'haarcascade_frontalface_alt.xml'
      USE_GIFSICLE_ENGINE: "True"
      SECURITY_KEY: "MY_SECURE_KEY"
      RESULT_STORAGE_STORES_UNSAFE: "True"
      RESULT_STORAGE: "thumbor.result_storages.file_storage"
    volumes:
      - data:/data
      - logs:/logs
    ports:
      - "8888:8000"
    networks:
      - my-net
  memcached:
    image: memcached
    ports:
      - "11211:11211"
    networks:
      - my-net
  db:
    image: "postgres:9.3"
    environment:
      LANG: en_US.utf8
      POSTGRES_PASSWORD: vagrant
      POSTGRES_USER: vagrant
      POSTGRES_DB: vagrant
      DB_UNACCENT: 'True'
    domainname: db.redegsti.dev
    hostname: database
    networks:
      - my-net
    ports:
      - "5432:5432"
    volumes:
      - ../postgres_database:/var/lib/postgresql
volumes:
  data:
    driver: local
  logs:
    driver: local
networks:
  my-net:
    driver: bridge
