version: '2'
services:
  thumbor:
    image: "apsl/thumbor"
    environment:
      SECURITY_KEY: 'MY_SECURE_KEY'
    ports: 
      - "8880:8000"
    domainname: thumbor.redegsti.dev
    hostname: thumbor
  memcached:
    image: memcached
    ports:
      - "11211:11211"
  db:
    image: "postgres:9.3"
    environment:
      LANG: en_US.utf8
      POSTGRES_PASSWORD: vagrant
      POSTGRES_USER: vagrant
      POSTGRES_DB: vagrant
      DB_UNACCENT: 'True'
    domainname: db.redegsti.dev
    hostname: database
    ports:
      - "5432:5432"
    volumes:
      - /srv/docker/postgres:/var/lib/postgresql
  web:
    build: .
    volumes:
      - ./:/var/www
    ports:
      - "8000:8000"
      - "2202:22"
    links:
      - db:db
      - thumbor:thumbor
      - memcached:memcached
    domainname: redegsti.dev
    hostname: redegsti