version: '2'
services:
  thumbor:
    extends:
        file: docker-compose.yml
        service: thumbor
  memcached:
    extends:
        file: docker-compose.yml
        service: memcached
  db:
    extends:
        file: docker-compose.yml
        service: db
networks:
  my-net:
    driver: bridge
