FROM postgres:9.3
RUN localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
ENV LANG en_US.utf8
ENV POSTGRES_PASSWORD vagrant
ENV POSTGRES_USER vagrant
ENV POSTGRES_DB vagrant
ENV DB_UNACCENT true