FROM phusion/baseimage:0.9.19
ENV HOME /root


# Use baseimage-docker's init system.
CMD ["/sbin/my_init"]

RUN rm -f /etc/service/sshd/down
RUN /etc/my_init.d/00_regen_ssh_host_keys.sh
RUN /usr/sbin/enable_insecure_key

ADD provision/data/thumbor.conf /root/thumbor.conf

#RUN apt-get update -yq &&\
# 	apt-get install -yq\
# 	build-essential python-dev python-pycurl python-pip\
# 	libopencv-dev python-numpy python-opencv webp libpng-dev libtiff-dev libjasper-dev libjpeg-dev

#RUN pip install thumbor
#RUN pip install colour
#RUN pip install opencv-engine

# Clean up APT when done.
RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


EXPOSE 22