# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-23 13:33
from __future__ import unicode_literals

from django.db import migrations
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancylocation',
            name='cities',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='state', chained_model_field='state', to='geography.City', verbose_name='Cidades'),
        ),
    ]
