# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0003_auto_20160503_1652'),
        ('job_vacancy', '0003_auto_20160503_0956'),
    ]

    operations = [
    ]
