# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-09 21:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='job_vacancy_responsibility',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Descri\xe7ao da resposabilidade'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='responsibility_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.JobVacancyResponsibilityType', verbose_name='tipo da \xe1rea de atua\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.Experience', verbose_name='Experi\xeancia'),
        ),
    ]
