# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-18 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0008_jobvacancy_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
    ]
