# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0010_auto_20160518_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Est\xe1 ativo'),
        ),
        migrations.AlterField(
            model_name='jobvacancyadditionalrequirement',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Requisito adicional'),
        ),
        migrations.AlterField(
            model_name='jobvacancycertification',
            name='exigency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.Exigency', verbose_name='Exig\xeancia'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='exigency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.Exigency', verbose_name='Exig\xeancia'),
        ),
    ]
