# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-29 18:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0011_auto_20160525_1107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='benefit',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='exigency',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobregime',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancys', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='benefits',
            field=models.ManyToManyField(blank=True, to='job_vacancy.Benefit', verbose_name='Benefits'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancys', to='company.Company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='contact',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Contact'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Is active'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='job_vacancy_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='job_vacancy_responsibility',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Responsibility Description'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='phone_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='workload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.WorkLoad', verbose_name='Work Load'),
        ),
        migrations.AlterField(
            model_name='jobvacancyadditionalrequirement',
            name='description',
            field=models.CharField(max_length=512, verbose_name='Aditional Requirement'),
        ),
        migrations.AlterField(
            model_name='jobvacancyadditionalrequirement',
            name='job_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_requirements', to='job_vacancy.JobVacancy', verbose_name='Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='jobvacancycertification',
            name='certification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certification.Certification', verbose_name='Certification'),
        ),
        migrations.AlterField(
            model_name='jobvacancycertification',
            name='exigency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.Exigency', verbose_name='Exigency'),
        ),
        migrations.AlterField(
            model_name='jobvacancycertification',
            name='job_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='job_vacancy.JobVacancy', verbose_name='Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='jobvacancylocation',
            name='job_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='job_vacancy.JobVacancy', verbose_name='Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='job_vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='resposibility', serialize=False, to='job_vacancy.JobVacancy', verbose_name='Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='responsibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='userprofile.Responsibility', verbose_name='Responsibility'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='responsibility_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.JobVacancyResponsibilityType', verbose_name='Responsibility Type'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibilitytype',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='level',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='exigency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.Exigency', verbose_name='Exigency'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='experience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.Experience', verbose_name='Experience'),
        ),
        migrations.AlterField(
            model_name='requirement',
            name='job_vacancy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requirements', to='job_vacancy.JobVacancy', verbose_name='Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='fixed_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Fixed value'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='job_vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='salary', serialize=False, to='job_vacancy.JobVacancy', verbose_name='Job Vacancy'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='range_value_from',
            field=models.FloatField(blank=True, null=True, verbose_name='Range from'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='range_value_to',
            field=models.FloatField(blank=True, null=True, verbose_name='Range to'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='regime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_vacancy.SalaryType', verbose_name='Salary Type'),
        ),
        migrations.AlterField(
            model_name='salarytype',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='workload',
            name='description',
            field=models.CharField(max_length=100, verbose_name='Description'),
        ),
    ]
