# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-14 13:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    replaces = [(b'job_vacancy', '0014_auto_20161110_1452'), (b'job_vacancy', '0015_auto_20161213_1525'), (b'job_vacancy', '0016_auto_20161213_1533'), (b'job_vacancy', '0017_auto_20161214_0949'), (b'job_vacancy', '0018_auto_20161214_1049')]

    dependencies = [
        ('job_vacancy', '0013_auto_20161028_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancylocation',
            name='cities',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='state', chained_model_field='state', null=True, to=b'geography.City', verbose_name='Cidades'),
        ),
        migrations.AlterField(
            model_name='jobvacancylocation',
            name='state',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='country', chained_model_field='country', null=True, on_delete=django.db.models.deletion.CASCADE, to='geography.State', verbose_name='Estados'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='home_office',
            field=models.BooleanField(default=False, verbose_name='Home Office'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='job_vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsibility', serialize=False, to='job_vacancy.JobVacancy', verbose_name='Vaga de trabalho'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancys', to='company.Company', verbose_name='Empresa'),
        ),
        migrations.RemoveField(
            model_name='salary',
            name='regime',
        ),
        migrations.AddField(
            model_name='benefit',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_type',
            field=models.PositiveIntegerField(choices=[(1, 'Interval'), (2, 'Fixed'), (3, 'Combine')], default=3, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='SalaryType',
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='observation',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Observation'),
        ),
    ]
