# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 18:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0014_auto_20161110_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='regime',
        ),
        migrations.AddField(
            model_name='benefit',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='observation',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.AddField(
            model_name='salary',
            name='salary_type',
            field=models.PositiveIntegerField(choices=[(1, 'Interval'), (2, 'Fixed'), (3, 'Combine')], default=3, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancys', to='company.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='home_office',
            field=models.BooleanField(default=False, verbose_name='Home Office'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='job_vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsibility', serialize=False, to='job_vacancy.JobVacancy', verbose_name='Vaga de trabalho'),
        ),
        migrations.DeleteModel(
            name='SalaryType',
        ),
    ]
