# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 18:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0014_auto_20161110_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='home_office',
            field=models.BooleanField(default=False, verbose_name='Home Office'),
        ),
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='job_vacancy',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='responsibility', serialize=False, to='job_vacancy.JobVacancy', verbose_name='Vaga de trabalho'),
        ),
    ]
