# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 18:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0015_auto_20161213_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='job_vacancys', to='company.Company', verbose_name='Empresa'),
        ),
    ]
