# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-19 19:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0015_auto_20170117_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancylocation',
            name='cities',
        ),
        migrations.RemoveField(
            model_name='jobvacancylocation',
            name='country',
        ),
        migrations.RemoveField(
            model_name='jobvacancylocation',
            name='job_vacancy',
        ),
        migrations.RemoveField(
            model_name='jobvacancylocation',
            name='state',
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='cities',
            field=models.ManyToManyField(blank=True, to='geography.City', verbose_name='Cidades'),
        ),
        migrations.AddField(
            model_name='jobvacancy',
            name='states',
            field=models.ManyToManyField(blank=True, to='geography.State', verbose_name='Estados'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Only number greater than 1 are permitted')], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_type',
            field=models.PositiveIntegerField(choices=[(1, 'Intervalo'), (2, 'Fixo'), (3, 'A Combinar')], default=3, verbose_name='Tipo'),
        ),
        migrations.DeleteModel(
            name='JobVacancyLocation',
        ),
    ]
