# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 12:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0016_auto_20170119_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Est\xe1 ativo'),
        ),
    ]
