# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-20 15:07
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0017_auto_20170120_0921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Only number greater than 1 are permitted')], verbose_name='Quantidade'),
        ),
    ]
