# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 18:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0020_auto_20170124_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancyresponsibility',
            name='responsibility',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='responsibility', to='userprofile.Responsibility', verbose_name='\xc1rea de atua\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_type',
            field=models.PositiveIntegerField(choices=[(None, '---------'), (1, 'Intervalo'), (2, 'Fixo'), (3, 'A Combinar')], default=3, verbose_name='Tipo'),
        ),
    ]
