# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 20:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0021_auto_20170124_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancyadditionalrequirement',
            name='description',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='Requisito adicional'),
        ),
    ]
