# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-24 21:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0022_auto_20170124_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='salary_type',
            field=models.PositiveIntegerField(choices=[(None, '---------'), (1, 'Intervalo'), (2, 'Fixo'), (3, 'A Combinar'), (4, 'Enviar pretens\xe3o salarial')], default=3, verbose_name='Tipo'),
        ),
    ]
