# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-26 12:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0023_auto_20170124_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobvacancy',
            name='contact',
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job vacancy E-mail'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='observation',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Aditional Observation'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job vacancy Web Site'),
        ),
    ]
