# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0024_auto_20170126_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='E-mail para contato'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='observation',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Observa\xe7\xe3o adicional'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='website para contato'),
        ),
    ]
