# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 19:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job_vacancy', '0025_auto_20170127_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobvacancy',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Job vacancy E-mail'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='observation',
            field=models.TextField(blank=True, max_length=10000, null=True, verbose_name='Aditional Observation'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1, message='Only number greater than 1 are permitted')], verbose_name='Quantidade'),
        ),
        migrations.AlterField(
            model_name='jobvacancy',
            name='site',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Job vacancy Web Site'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='salary_type',
            field=models.PositiveIntegerField(choices=[(None, '---------'), (1, 'Intervalo'), (2, 'Fixo'), (3, 'A Combinar'), (4, 'Send salary')], default=3, verbose_name='Tipo'),
        ),
    ]
