# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-23 18:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('useralerts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralert',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Publish')], default=1),
        ),
        migrations.AddField(
            model_name='useralert',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
