# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useralerts', '0002_auto_20160823_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useralert',
            name='status',
            field=models.IntegerField(choices=[(1, 'Draft'), (2, 'Publish'), (3, 'Sended')], default=1),
        ),
    ]
