# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('useralerts', '0003_auto_20160824_1121'),
    ]

    operations = [
        migrations.AddField(
            model_name='useralert',
            name='type',
            field=models.IntegerField(choices=[(1, 'Info'), (2, 'Warning'), (3, 'Danger')], default=1),
        ),
    ]
