# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-08 17:54
from __future__ import unicode_literals

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160401_1425'),
    ]

    operations = [
        UnaccentExtension()
    ]
