# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 18:59
from __future__ import unicode_literals
from django.contrib.postgres.operations import UnaccentExtension

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [

        UnaccentExtension()
    ]

