# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 20:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20160404_1559'),
        ('core', '0003_unnacent'),
    ]

    operations = [
    ]
