# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-29 19:20
from __future__ import unicode_literals
from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    def update_site(apps, schema_editor):

        Site = apps.get_model("sites", "Site")

        current_site = Site.objects.get(id=settings.SITE_ID)
        current_site.domain = 'www.portalgsti.com.br'
        current_site.name = 'Portal GSTI'

        current_site.save()

    dependencies = [
        ('core', '0004_merge'),
    ]

    operations = [
        migrations.RunPython(update_site),
    ]
