# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 19:57
from __future__ import unicode_literals

import apps.core.models.course
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0002_taxonomy_update_in'),
        ('core', '0005_auto_20160929_1620'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('description', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3, verbose_name='Rating')),
                ('external_author', models.TextField(max_length=255, verbose_name='External Author')),
                ('updatein', models.DateTimeField(auto_now=True)),
                ('curriculum', models.TextField(max_length=255, verbose_name='Curriculum')),
                ('image', models.ImageField(blank=True, upload_to=apps.core.models.course.course_image_upload, verbose_name='Imagem')),
                ('affiliate_link', models.URLField(verbose_name='Affiliate link')),
                ('internal_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Internal author')),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('description', models.CharField(max_length=255, verbose_name='Descri\xe7\xe3o')),
                ('acronym', models.CharField(max_length=10, verbose_name='Acronym')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='core.Language', verbose_name='Languages'),
        ),
        migrations.AddField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_related_courses_+', to='core.Course', verbose_name='Related Courses'),
        ),
        migrations.AddField(
            model_name='course',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, related_name='taxonomies', to='taxonomy.Taxonomy', verbose_name='Taxonomy'),
        ),
    ]
