# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20161124_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='slug',
            field=models.SlugField(default='', max_length=200, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
