# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_course_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='external_author',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='External Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='internal_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Internal author'),
        ),
    ]
