# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-25 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20161125_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, related_name='courses', to='taxonomy.Taxonomy', verbose_name='Taxonomy'),
        ),
    ]
