# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 17:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20161129_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='comment',
            field=models.TextField(blank=True, max_length=1024, null=True),
        ),
    ]
