# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-29 20:13
from __future__ import unicode_literals

import apps.core.models.rating
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rating_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', validators=[apps.core.models.rating.content_in_settings]),
        ),
    ]
