# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 12:55
from __future__ import unicode_literals

import apps.core.models.rating
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20161129_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.PositiveSmallIntegerField(max_length=5, validators=[apps.core.models.rating.max_float]),
        ),
    ]
