# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-30 13:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0014_auto_20161130_0955'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set([('content_type', 'object_id', 'author')]),
        ),
    ]
