# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-02 12:24
from __future__ import unicode_literals

import apps.core.models.rating
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20161130_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='value',
            field=models.DecimalField(decimal_places=2, max_digits=3, validators=[apps.core.models.rating.max_float]),
        ),
    ]
