# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20161202_0924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='curriculum',
        ),
    ]
