# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_remove_course_curriculum'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='T\xedtulo')),
                ('description', models.TextField(verbose_name='Descri\xe7\xe3o')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.Course', verbose_name='Course')),
            ],
        ),
    ]
