# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 21:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20161205_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='class_link',
            field=models.URLField(null=True, verbose_name='Class Link'),
        ),
    ]
