# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-05 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_course_class_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='class_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link da aula'),
        ),
        migrations.AlterField(
            model_name='course',
            name='plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.Plataform', verbose_name='Plataforma'),
        ),
    ]
