# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20161205_1859'),
        ('core', '0007_auto_20161208_1111'),
    ]

    operations = [
    ]
