# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 18:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20161209_1426'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='external_author_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='External Author - Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='External Author'),
        ),
    ]
