# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20161212_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='embed',
            field=models.TextField(blank=True, null=True, verbose_name='Embed'),
        ),
    ]
