# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_course_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='embed',
            field=models.TextField(blank=True, help_text=b'class: embed-responsive-item', null=True, verbose_name='Embed'),
        ),
    ]
