# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 21:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_auto_20161212_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='embed',
            field=models.TextField(blank=True, help_text=b'class="embed-responsive-item"', null=True, verbose_name='Embed'),
        ),
    ]
