# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-12 21:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20161212_1811'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='curriculum',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='curriculum',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Ordem'),
        ),
    ]
