# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-13 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_auto_20161212_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 to free courses, blank to unknow price', max_digits=6, null=True, verbose_name='Price'),
        ),
    ]
