# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 16:51
from __future__ import unicode_literals

import apps.core.models.course
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20161215_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link afiliado'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_link',
            field=models.URLField(blank=True, null=True, verbose_name='Link da Aula'),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Autor externo'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.core.models.course.course_image_upload, verbose_name='Imagens'),
        ),
        migrations.AlterField(
            model_name='course',
            name='internal_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Autor interno'),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='core.Language', verbose_name='Linguagens'),
        ),
        migrations.AlterField(
            model_name='course',
            name='plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.Plataform', verbose_name='Plataforma'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Avalia\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_related_courses_+', to='core.Course', verbose_name='Cursos realacionados'),
        ),
        migrations.AlterField(
            model_name='course',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, related_name='courses', to='taxonomy.Taxonomy', verbose_name='Taxonomia'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.Course', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='language',
            name='acronym',
            field=models.CharField(max_length=10, verbose_name='Sigla'),
        ),
    ]
