# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 17:45
from __future__ import unicode_literals

import apps.core.models.course
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20161230_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='external_author_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Autor externo - Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='course',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observa\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 para cursos gr\xe1tis, branco para pre\xe7o desconhecido', max_digits=6, null=True, verbose_name='Pre\xe7o'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.course.course_thumb_upload, verbose_name='Miniatura'),
        ),
    ]
