# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-16 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_auto_20170106_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AddField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Date'),
        ),
    ]
