# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_auto_20161213_1525'),
        ('core', '0037_auto_20170116_2042'),
    ]

    operations = [
    ]
