# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-03-14 18:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20170117_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Descri\xe7\xe3o'),
        ),
    ]
