# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:34
from __future__ import unicode_literals

import apps.core.models.course
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_auto_20170316_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='active',
            field=models.BooleanField(default=True, verbose_name='A\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='course',
            name='affiliate_link',
            field=models.URLField(blank=True, null=True, verbose_name='Affiliate link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='class_link',
            field=models.URLField(blank=True, null=True, verbose_name='Class Link'),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(max_length=400, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Due Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_author',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='External Author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='external_author_description',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='External Author - Description'),
        ),
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.core.models.course.course_image_upload, verbose_name='Imagem'),
        ),
        migrations.AlterField(
            model_name='course',
            name='internal_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to=settings.AUTH_USER_MODEL, verbose_name='Internal author'),
        ),
        migrations.AlterField(
            model_name='course',
            name='languages',
            field=models.ManyToManyField(blank=True, related_name='languages', to='core.Language', verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='course',
            name='observation',
            field=models.TextField(blank=True, null=True, verbose_name='Observation'),
        ),
        migrations.AlterField(
            model_name='course',
            name='plataform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.Plataform', verbose_name='Plataform'),
        ),
        migrations.AlterField(
            model_name='course',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='0 to free courses, blank to unknow price', max_digits=6, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='course',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='Rating'),
        ),
        migrations.AlterField(
            model_name='course',
            name='related_courses',
            field=models.ManyToManyField(blank=True, related_name='_course_related_courses_+', to='core.Course', verbose_name='Related Courses'),
        ),
        migrations.AlterField(
            model_name='course',
            name='start_date',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='course',
            name='taxonomies',
            field=models.ManyToManyField(blank=True, related_name='courses', to='taxonomy.Taxonomy', verbose_name='Taxonomy'),
        ),
        migrations.AlterField(
            model_name='course',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apps.core.models.course.course_thumb_upload, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='course',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curriculums', to='core.Course', verbose_name='Course'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='curriculum',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='language',
            name='acronym',
            field=models.CharField(max_length=10, verbose_name='Acronym'),
        ),
        migrations.AlterField(
            model_name='language',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='plataform',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date'),
        ),
    ]
