# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configkey',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_keys', to='configuration.ConfigGroup', verbose_name='COnfigurar chaves'),
        ),
    ]
