# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configuration', '0013_auto_20171003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configkey',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_keys', to='configuration.ConfigGroup', verbose_name='COnfigurar chaves'),
        ),
        migrations.AlterField(
            model_name='configvalues',
            name='key',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='config_values', to='configuration.ConfigKey', verbose_name='Configurar Chaves'),
        ),
    ]
