# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-26 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xptransaction',
            name='communitiy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='community.Community', verbose_name='Community'),
        ),
    ]
