# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-27 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0002_auto_20171026_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='xptransaction',
            old_name='communitiy',
            new_name='community',
        ),
    ]
