# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0004_auto_20171027_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrank',
            name='value',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
