# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-28 14:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0005_auto_20171028_0937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrank',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Value'),
        ),
    ]
