# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0007_auto_20171028_1139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrank',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='community.Community', verbose_name='Comunidade'),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='community.Community', verbose_name='Comunidade'),
        ),
    ]
