# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0009_communityrank_rank_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communityrank',
            name='community',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rank', to='community.Community', verbose_name='Community'),
        ),
        migrations.AlterField(
            model_name='xptransaction',
            name='community',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='community.Community', verbose_name='Community'),
        ),
    ]
