# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-27 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_auto_20170117_1513'),
        ('certification', '0015_auto_20170126_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='courses',
            field=models.ManyToManyField(related_name='certifications', to='core.Course', verbose_name='Courses'),
        ),
        migrations.AddField(
            model_name='certification',
            name='guide',
            field=models.URLField(blank=True, null=True, verbose_name='Guide link'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='where_get',
            field=models.TextField(blank=True, null=True, verbose_name='Where get'),
        ),
    ]
