# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-07-03 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0017_auto_20170220_1706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='courses',
            field=models.ManyToManyField(related_name='certifications', to='core.Course', verbose_name='Courses'),
        ),
    ]
