# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0019_auto_20171003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='courses',
            field=models.ManyToManyField(related_name='certifications', to='core.Course', verbose_name='Cursos'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='more_info',
            field=models.TextField(blank=True, null=True, verbose_name='Mais informa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='T\xedtulo'),
        ),
    ]
