# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('certification', '0020_auto_20180202_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='courses',
            field=models.ManyToManyField(related_name='certifications', to='core.Course', verbose_name='Courses'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='description',
            field=models.TextField(max_length=10000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='more_info',
            field=models.TextField(blank=True, null=True, verbose_name='More info'),
        ),
        migrations.AlterField(
            model_name='certification',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Title'),
        ),
    ]
