# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome')),
                ('logo', models.ImageField(blank=True, default='', upload_to='company/%Y/%m/%d', verbose_name='Logo')),
            ],
        ),
    ]
