# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 19:17
from __future__ import unicode_literals

import apps.company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taxonomy', '0002_taxonomy_update_in'),
        ('company', '0015_merge_20160922_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.PositiveSmallIntegerField(validators=[apps.company.models.limit_to_membershiptypes], verbose_name='Permission')),
            ],
        ),
        migrations.AddField(
            model_name='company',
            name='taxonomies',
            field=models.ManyToManyField(related_name='companies', to='taxonomy.Taxonomy', verbose_name='Taxonomies'),
        ),
        migrations.AddField(
            model_name='company',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Empresa'),
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usu\xe1rio'),
        ),
        migrations.AddField(
            model_name='company',
            name='members',
            field=models.ManyToManyField(related_name='companies', through='company.Membership', to=settings.AUTH_USER_MODEL),
        ),
    ]
