# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0016_auto_20161206_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, upload_to='company/%Y/%m/%d', verbose_name='Logo'),
        ),
    ]
