# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-08 14:37
from __future__ import unicode_literals

import apps.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0017_auto_20161208_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Admin'), (2, 'Collaborator')], validators=[apps.company.models.limit_to_membershiptypes], verbose_name='Permission'),
        ),
    ]
