# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-28 16:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('company', '0021_auto_20161215_1634'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='membership',
            unique_together=set([('user', 'company', 'permission')]),
        ),
    ]
