# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-30 16:51
from __future__ import unicode_literals

import apps.company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0022_auto_20161228_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='taxonomies',
            field=models.ManyToManyField(related_name='companies', to='taxonomy.Taxonomy', verbose_name='Taxonomias'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, '^admin-portal/'), (2, 'Colaborador')], validators=[apps.company.models.limit_to_membershiptypes], verbose_name='Permiss\xe3o'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome de usu\xe1rio'),
        ),
    ]
