# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-04 13:59
from __future__ import unicode_literals

import apps.company.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0023_auto_20161230_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(upload_to='company/%Y/%m/%d', verbose_name='Logo'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Colaborador')], validators=[apps.company.models.limit_to_membershiptypes], verbose_name='Permiss\xe3o'),
        ),
    ]
