# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0021_auto_20161213_1525'),
        ('company', '0025_auto_20170106_1445'),
    ]

    operations = [
    ]
