# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 18:14
from __future__ import unicode_literals

import apps.company.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0028_auto_20171003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='company',
            name='taxonomies',
            field=models.ManyToManyField(related_name='companies', to='taxonomy.Taxonomy', verbose_name='Taxonomias'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='companycontact',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='companycontacttype',
            name='description',
            field=models.CharField(max_length=255, verbose_name='Descri\xe7\xe3o'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.Company', verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='permission',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Administrator'), (2, 'Colaborador')], validators=[apps.company.models.limit_to_membershiptypes], verbose_name='Permiss\xe3o'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Nome de usu\xe1rio'),
        ),
    ]
