# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-15 14:43
from __future__ import unicode_literals

import apps.account.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20160906_1200'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', apps.account.manager.UserManager()),
            ],
        ),
    ]
