# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-16 12:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20160915_1528'),
        ('account', '0003_auto_20160915_1143'),
    ]

    operations = [
    ]
