# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-06 19:19
from __future__ import unicode_literals

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20160920_1006'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='usertype',
            field=models.PositiveSmallIntegerField(default=1, validators=[apps.account.models.limit_usertypes_to], verbose_name='User type'),
        ),
    ]
