# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-06 17:45
from __future__ import unicode_literals

import apps.account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_usertype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='usertype',
            field=models.PositiveSmallIntegerField(default=1, validators=[apps.account.models.limit_usertypes_to], verbose_name='Tipo de usu\xe1rio'),
        ),
    ]
