# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-31 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_xp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gamification_member',
            field=models.BooleanField(default=True, verbose_name='Gamification Member'),
        ),
    ]
