# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-10 20:20
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socialactions', '0002_auto_20161010_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='target_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useractioncounter',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_counter', to=settings.AUTH_USER_MODEL),
        ),
    ]
