# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-23 12:31
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(blank=True, null=True),
        ),
    ]
