# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0002_question_search_vector'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('change_other_questions', 'Can edit questions from others')]},
        ),
    ]
