# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:14
from __future__ import unicode_literals

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_auto_20160923_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
