# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-20 11:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_auto_20161013_1414'),
        ('question', '0003_auto_20161019_1043'),
    ]

    operations = [
    ]
