# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0005_merge_20161020_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='comment_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='dislike_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='like_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
