# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-03 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0006_auto_20161102_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='comment_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislike_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='like_count',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
