# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0008_auto_20161206_1617'),
        ('question', '0008_auto_20161124_1654'),
    ]

    operations = [
    ]
