# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0009_merge_20161209_1418'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('change_other_questions', 'Can edit questions from others')]},
        ),
    ]
