# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0010_auto_20171003_1134'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('change_other_questions', 'Permiss\xe3o para editar perguntas de outros autores')]},
        ),
    ]
