# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0011_auto_20180202_1514'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'permissions': [('change_other_questions', 'Can edit questions from others')]},
        ),
    ]
