# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publishin',
            field=models.DateTimeField(db_index=True, null=True),
        ),
    ]
