# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-01 18:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20160901_1548'),
        ('article', '0013_article_first_slug'),
    ]

    operations = [
    ]
