# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-20 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0018_article_vector_title_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='vector_title_text',
            new_name='search_vector',
        ),
    ]
