# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20160905_1710'),
        ('article', '0019_auto_20160920_1518'),
    ]

    operations = [
    ]
