# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:15
from __future__ import unicode_literals

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0019_auto_20160920_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, upload_to=apps.article.models.article_image_upload),
        ),
    ]
