# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-13 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20161013_1415'),
        ('article', '0020_merge_20160922_1422'),
    ]

    operations = [
    ]
