# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0020_auto_20161013_1415'),
        ('article', '0021_auto_20161013_1412'),
    ]

    operations = [
    ]
