# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20161019_1042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_other_articles', 'Can edit articles from others')]},
        ),
    ]
