# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-19 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0024_auto_20161019_1042'),
        ('article', '0021_merge_20161013_1426'),
    ]

    operations = [
    ]
