# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-01 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_auto_20161101_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='dislike_count',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='like_count',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
