# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-08 12:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0025_merge_20161019_1736'),
        ('article', '0028_auto_20161103_1537'),
    ]

    operations = [
    ]
