# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-10 17:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0029_merge_20161108_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_other_articles', 'Can edit articles from others')]},
        ),
    ]
