# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0030_auto_20161110_1452'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'permissions': [('change_other_articles', 'Permiss\xe3o para editar artigos de outros autores')]},
        ),
    ]
