# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-02 14:17
from __future__ import unicode_literals

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0031_auto_20161124_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image_height',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='image_width',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, height_field=b'image_height', upload_to=apps.article.models.article_image_upload, width_field=b'image_width'),
        ),
    ]
