# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-20 20:06
from __future__ import unicode_literals

import apps.article.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0032_auto_20170202_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='text',
            field=models.TextField(max_length=100000, validators=[apps.article.models.validate_min_text]),
        ),
    ]
