# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0001_initial'),
        ('community', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relevance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('object_id', models.PositiveIntegerField()),
                ('official', models.BooleanField(default=False)),
                ('communities', models.ManyToManyField(related_name='feeds', to='community.Community')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('tags', models.ManyToManyField(related_name='feeds', to='core.Tags')),
                ('taxonomies', models.ManyToManyField(related_name='feeds', to='taxonomy.Taxonomy')),
            ],
        ),
    ]
