# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-17 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20160629_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedobject',
            name='seo_no_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='feedobject',
            name='seo_no_index',
            field=models.BooleanField(default=False),
        ),
    ]
