# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 20:30
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0003_auto_20161017_1003'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=256)),
                ('updatein', models.DateTimeField(auto_now=True)),
                ('publishin', models.DateTimeField(db_index=True, null=True)),
                ('comment_count', models.PositiveIntegerField(blank=True, null=True)),
                ('like_count', models.PositiveIntegerField(blank=True, null=True)),
                ('dislike_count', models.PositiveIntegerField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_status', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
            ],
        ),
    ]
