# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-15 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0004_profilestatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilestatus',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
