# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 19:02
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0006_profilestatus_search_vector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='publishin',
            field=models.DateTimeField(db_index=True, default=datetime.datetime(2017, 2, 16, 19, 2, 43, 362504, tzinfo=utc), null=True),
        ),
    ]
