# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-02-16 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0007_auto_20170216_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='publishin',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, null=True),
        ),
    ]
