# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0009_auto_20170610_1133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilestatus',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_status', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
    ]
