# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-23 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0011_auto_20180202_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedobject',
            name='seo_no_follow',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='feedobject',
            name='seo_no_index',
            field=models.BooleanField(default=False),
        ),
    ]
