# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 13:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=150)),
                ('description', models.TextField(max_length=2048)),
                ('image', models.ImageField(blank=True, default=b'', upload_to=b'community/%Y/%m/%d')),
                ('relevance', models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ('related', models.ManyToManyField(blank=True, related_name='related_community', to='community.Community', verbose_name='Comunidade relacionada')),
                ('taxonomy', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='community_related', to='taxonomy.Taxonomy')),
            ],
        ),
    ]
