# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='related',
            field=models.ManyToManyField(related_name='_community_related_+', to='community.Community'),
        ),
    ]
