# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 14:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_community_related'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='related',
            field=models.ManyToManyField(related_name='_community_related_+', to='community.Community', verbose_name='Community Related'),
        ),
    ]
