# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-28 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0015_auto_20161013_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='community',
            name='update_in',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
