# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-07 20:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0016_merge_20161013_1426'),
        ('community', '0016_community_update_in'),
    ]

    operations = [
    ]
