# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-10-03 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0017_merge_20161107_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='community',
            name='related',
            field=models.ManyToManyField(blank=True, related_name='related_community', to='community.Community', verbose_name='Community Related'),
        ),
    ]
