# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-06 12:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_auto_20160425_1924'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='responsibility',
            options={'ordering': ('name',)},
        ),
    ]
