# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-26 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_auto_20160906_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
