# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 12:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_userprofile_last_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
