# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-26 19:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('userprofile', '0006_auto_20161026_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsibility',
            name='categories',
            field=models.ManyToManyField(related_name='responsibilities', to='taxonomy.Taxonomy'),
        ),
    ]
