# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-02 14:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0010_autoupdate_responsibilities_slugs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='slug',
            field=models.SlugField(blank=True, default=''),
            preserve_default=False,
        ),
    ]
