# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-24 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0013_auto_20161118_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
    ]
