# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-12-09 17:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0015_auto_20161205_1739'),
        ('userprofile', '0015_auto_20161207_1026'),
    ]

    operations = [
    ]
