# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2017-01-17 18:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0020_auto_20161230_1351'),
        ('userprofile', '0019_auto_20161213_1525'),
    ]

    operations = [
    ]
