# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2018-02-02 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0025_auto_20171003_1134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='categories',
            field=models.ManyToManyField(related_name='responsibilities', to='taxonomy.Taxonomy', verbose_name='Categorias'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='main_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Principais atividades'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='more_info',
            field=models.TextField(blank=True, null=True, verbose_name='Mais informa\xe7\xf5es'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='study',
            field=models.TextField(blank=True, null=True, verbose_name='O que estudar'),
        ),
    ]
