# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-08-01 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0026_auto_20180202_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='responsibility',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='categories',
            field=models.ManyToManyField(related_name='responsibilities', to='taxonomy.Taxonomy', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='main_activity',
            field=models.TextField(blank=True, null=True, verbose_name='Main Activities'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='more_info',
            field=models.TextField(blank=True, null=True, verbose_name='More info'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='name',
            field=models.CharField(max_length=60, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='responsibility',
            name='study',
            field=models.TextField(blank=True, null=True, verbose_name='What study'),
        ),
    ]
