# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-17 12:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taxonomy',
            options={'ordering': ('description',)},
        ),
    ]
