# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-18 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_auto_20160317_0946'),
        ('taxonomy', '0002_auto_20160317_1526'),
    ]

    operations = [
    ]
