# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-14 22:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('type', models.IntegerField(choices=[(1, 'Info'), (2, 'Danger'), (3, 'Warning'), (4, 'Sucesso')])),
                ('updated_in', models.DateTimeField(auto_now=True, verbose_name='Updated In')),
                ('created_in', models.DateTimeField(auto_now_add=True, verbose_name='Created In')),
            ],
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
