# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-08-24 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0010_auto_20160822_1649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_action',
            field=models.PositiveIntegerField(choices=[(1, b'like'), (2, b'unlike'), (3, b'follow'), (4, b'favourite'), (5, b'suggest'), (6, b'comment'), (7, b'see-later'), (8, b'answer'), (9, b'alert'), (10, b'useralert')]),
        ),
    ]
