# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-22 17:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0014_auto_20160905_1710'),
        ('notifications', '0016_auto_20160920_1006'),
    ]

    operations = [
    ]
